# METABEGIN
# X-Env-Layer-Name: vimrc-config
# METAEND
---
name: vimrc-config
docs: Turn on syntax highlighting for all users.
hooks:
  bdebstrap:
    - phase: post-bootstrap
      chroot: true
      run: |
        set -e
        # For any user, including those created later by Raspberry Pi Imager's first-boot user setup.
        mkdir -p /etc/vim
        echo 'syntax on' >> /etc/vim/vimrc.local

        # For any future users created with adduser.
        mkdir -p /etc/skel
        printf '%s\n' 'syntax on' > /etc/skel/.vimrc
